### ISSUE TITLE
win 10 无法正常工作

### ISSUE THREAD

**Issue by forlin** [difcareer/sqlmap4burp#2]
作者你好，请问还更新吗？

我已经将python变量和sqlmap都设置了环境变成 但还是无法正常工作

运行时直接提示

`        ___
       __H__
 ___ ___[']_____ ___ ___  {1.0.12.10#dev}
|_ -| . [']     | .'| . |
|___|_  [']_|_|_|__,|  _|
      |_|V          |_|   http://sqlmap.org

Usage: sqlmap.py [options]

sqlmap.py: error: missing a mandatory option (-d, -u, -l, -m, -r, -g, -c, -x, --wizard, --update, --purge-output or --dependencies), use -h for basic or -hh for advanced help

Press Enter to continue...`

**Comment by mactavishmeng** [comment]
看这个回显应该是你在cmd中直接输入了sqlmap.py吧，提示你没有带参数，后面跟上参数就可以正常用了。装好插件之后输入的命令是一些选项，比如level-3之类。
